# Generated by Django 4.0.4 on 2022-05-02 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventor', '0004_alter_investor_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_inventor', models.BooleanField(default=True, null=True)),
                ('published_date', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(max_length=250)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('likes', models.IntegerField(null=True)),
                ('industry', models.CharField(choices=[('a', 'Entertainment'), ('b', 'Handcraft'), ('c', 'Medical'), ('d', 'Artificial Intelligence'), ('e', 'Clothing'), ('f', 'Fintech'), ('g', 'Engineering'), ('h', 'Agriculture'), ('i', 'Aircraft'), ('j', 'Design'), ('k', 'Sport'), ('l', 'Technology')], max_length=1)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
