# Generated by Django 4.0.4 on 2022-05-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventor', '0005_inventions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventions',
            name='likes',
        ),
        migrations.AddField(
            model_name='inventions',
            name='tag',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
