# Generated by Django 4.0.4 on 2022-05-02 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventor', '0006_remove_inventions_likes_inventions_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventions',
            name='invention_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=250)),
                ('category', models.CharField(choices=[('a', 'Entertainment'), ('b', 'Handcraft'), ('c', 'Medical'), ('d', 'Artificial Intelligence'), ('e', 'Clothing'), ('f', 'Fintech'), ('g', 'Engineering'), ('h', 'Agriculture'), ('i', 'Aircraft'), ('j', 'Design'), ('k', 'Sport'), ('l', 'Technology')], max_length=1)),
                ('Invention', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventor.inventions')),
                ('investor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventor.investor')),
            ],
        ),
    ]
