# Generated by Django 4.0.4 on 2022-05-02 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventor', '0009_alter_investment_investor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='Invention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventor.inventions'),
        ),
    ]
