# Generated by Django 4.0.4 on 2022-05-02 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventor', '0010_alter_investment_invention'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='category',
        ),
        migrations.AlterField(
            model_name='investment',
            name='Invention',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventor.inventions'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='investor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
