# Generated by Django 4.0.4 on 2022-05-02 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventor', '0011_remove_investment_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='investor',
        ),
    ]
