# Generated by Django 4.0.4 on 2022-05-02 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventor', '0012_remove_investment_investor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='Invention',
        ),
    ]
