# Generated by Django 4.0.4 on 2022-05-02 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventor', '0013_remove_investment_invention'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='Invention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventions', to='inventor.inventions'),
        ),
    ]
