# Generated by Django 4.0.4 on 2022-05-02 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventor', '0015_remove_investment_invention_investment_is_investor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='Invention',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventor.inventions'),
        ),
    ]
