# Generated by Django 4.0.4 on 2022-05-02 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventor', '0017_remove_investment_invention_investment_inventor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='Inventor',
        ),
        migrations.AddField(
            model_name='investment',
            name='inventions',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventor.inventions'),
        ),
    ]
