# Generated by Django 4.0.4 on 2022-05-03 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventor', '0018_remove_investment_inventor_investment_inventions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='user',
        ),
    ]
