# Generated by Django 4.0.4 on 2022-05-03 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventor', '0019_remove_investment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment',
            old_name='inventions',
            new_name='Invents',
        ),
    ]
