# Generated by Django 4.0.4 on 2022-05-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventor', '0024_remove_inventions_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='facabook_url',
        ),
        migrations.AlterField(
            model_name='inventions',
            name='industry',
            field=models.CharField(choices=[('E', 'Entertainment'), ('H', 'Handcraft'), ('M', 'Medical'), ('A', 'Artificial Intelligence'), ('C', 'Clothing'), ('F', 'Fintech'), ('N', 'Engineering'), ('G', 'Agriculture'), ('R', 'Aircraft'), ('D', 'Design'), ('S', 'Sport'), ('T', 'Technology')], max_length=1),
        ),
    ]
