# Generated by Django 4.0.4 on 2022-05-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventor', '0025_remove_investor_facabook_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='facabook_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
