# Generated by Django 4.0.4 on 2022-05-03 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventor', '0026_investor_facabook_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='Invents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventor.inventions'),
        ),
    ]
