# Generated by Django 4.0.4 on 2022-05-03 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventor', '0027_alter_investment_invents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='Invents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
