# Generated by Django 4.0.4 on 2022-05-07 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventor', '0030_inventions_user_investment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventions',
            name='user',
        ),
        migrations.AddField(
            model_name='inventions',
            name='inventorr',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventor.inventor'),
        ),
    ]
