# Generated by Django 4.0.4 on 2022-05-07 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventor', '0031_remove_inventions_user_inventions_inventorr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventions',
            name='inventorr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventor.inventor'),
        ),
    ]
