# Generated by Django 4.0.4 on 2022-05-07 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventor', '0036_rename_investor_investment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='is_investor',
        ),
    ]
