# Generated by Django 4.0.4 on 2022-05-07 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventor', '0037_remove_investment_is_investor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventions',
            name='inventorr',
        ),
        migrations.AddField(
            model_name='inventions',
            name='Inventor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventor.inventor'),
        ),
    ]
