# Generated by Django 4.0.4 on 2022-05-07 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventor', '0038_remove_inventions_inventorr_inventions_inventor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventions',
            name='Inventor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
