# Generated by Django 4.0.4 on 2022-05-08 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventor', '0039_alter_inventions_inventor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investor',
            old_name='facabook_url',
            new_name='facebook_url',
        ),
    ]
