# Generated by Django 4.0.4 on 2022-06-28 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventor', '0042_inventor_country_inventor_first_name_inventor_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='image')),
            ],
        ),
        migrations.RemoveField(
            model_name='inventions',
            name='Inventor',
        ),
        migrations.RemoveField(
            model_name='inventions',
            name='image',
        ),
        migrations.RemoveField(
            model_name='inventions',
            name='is_inventor',
        ),
        migrations.AddField(
            model_name='inventions',
            name='additional_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventions',
            name='amount_needed_to_start',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='inventions',
            name='banner',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
        migrations.AddField(
            model_name='inventions',
            name='business_model',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='inventions',
            name='currency',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='inventions',
            name='current_budget',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='inventions',
            name='equity_per_invest',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='inventions',
            name='expansion_plans',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='inventions',
            name='invention_caption',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='inventions',
            name='invention_timeline',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='inventions',
            name='invention_url',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='inventions',
            name='inventor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventions',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventions',
            name='number_of_investors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventions',
            name='related_industry',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='inventions',
            name='required_amount',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='inventions',
            name='revenue_generating_stractegy',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='inventions',
            name='sum_required_to_complete',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='inventions',
            name='target_audience',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='inventions',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventions',
            name='tag',
            field=models.CharField(blank=True, choices=[('M', 'Music'), ('P', 'Potray'), ('G', 'Games'), ('E', 'Events'), ('S', 'Sea'), ('O', 'Ocean'), ('B', 'Building'), ('T', 'Technology'), ('W', 'Water'), ('J', 'Jogging'), ('e', 'etc')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='inventions',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventor.inventionimage'),
        ),
    ]
