# Generated by Django 4.0.4 on 2022-06-28 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventor', '0043_inventionimage_remove_inventions_inventor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventions',
            name='banner',
        ),
    ]
