# Generated by Django 4.0.4 on 2022-06-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventor', '0044_remove_inventions_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='company_address',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='company_email',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='head_office',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='hobbies',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='url',
        ),
        migrations.AddField(
            model_name='user',
            name='company_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='company_email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='facebook_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='head_office',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hobbies',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
