# Generated by Django 4.0.4 on 2022-06-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventor', '0046_remove_investor_image_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='state',
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
