# Generated by Django 4.0.4 on 2022-06-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventor', '0047_remove_investor_state_user_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='image',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
