# Generated by Django 4.0.4 on 2022-07-18 16:30

from django.db import migrations, models
import inventor.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventor', '0051_inventions_invention_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventions',
            name='invention_image',
            field=models.ImageField(blank=True, null=True, upload_to=inventor.models.nameFile),
        ),
        migrations.AlterField(
            model_name='inventions',
            name='inventor_image',
            field=models.ImageField(blank=True, null=True, upload_to=inventor.models.nameFile),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=inventor.models.nameFile),
        ),
    ]
